class SwitchInterface(BaseException):

    def __init__(self, name: str) -> None:
        self.name = name


class InterfaceExistsError(BaseException): ...
class InterfaceNotFoundError(BaseException): ...

class ActivatedInterfaceError(BaseException): ...
class DeactivatedInterfaceError(BaseException): ...

class QuitPygame(BaseException): ...
